# Generated by Django 4.2.5 on 2023-10-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_idnp_alter_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default=1234567, max_length=8, unique=True),
            preserve_default=False,
        ),
    ]
